repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.5'
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/prettier/pre-commit
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [css, javascript, json, markdown, yaml]
