name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Or '3.9' as per project preference
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff black pytest
      - name: Run Ruff (linting)
        run: ruff check .
      - name: Run Black (formatting check)
        run: black --check .
      - name: Run Pytest (tests)
        run: pytest
